image:
  name: ruby:2.5.0

variables:
  POSTGRES_DB: dit_test
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"

services:
  - name: redis:3.2.7
  - name: postgres:9.6-alpine
    alias: postgres

stages:
  - test

test:
  stage: test
  before_script:
    - apt-get update -qy
    - apt-get install -y postgresql-client
    - apt-get install -y nodejs
    - bundle install --jobs 4 --retry 3 --path vendor
    - RAILS_ENV=test bundle exec rake db:create db:migrate
  script:
    - RAILS_ENV=test RAILS_DISABLE_TEST_LOG=true bundle exec rspec spec/ --tag '~skip_ci' --format RspecJunitFormatter --out rspec.xml --format progress
  cache:
    key: gems-cache
    paths:
      - vendor/ruby
