image:
  name: ruby:2.5.0

variables:
  POSTGRES_DB: dit_test
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"

services:
  - name: redis:3.2.7
    alias: redis
  - name: postgres:9.6-alpine
    alias: postgres

stages:
  - test

test:
  stage: test
  before_script:
    - apt-get update -qy
    - apt-get install -y postgresql-client
    - apt-get install -y nodejs
    - bundle install --jobs 4 --retry 3 --path=cache/bundler
    - RAILS_ENV=test bundle exec rake db:create --trace
    - RAILS_ENV=test SCHEMA=db/structure.sql bundle exec rake db:structure:load --trace
  script:
    - RAILS_ENV=test RAILS_DISABLE_TEST_LOG=true bundle exec rspec spec/ --tag '~skip_ci' --format RspecJunitFormatter --out rspec.xml --format progress

cache:
  key: gems-cache
  paths:
    - vendor/ruby
    - vendor/bundle
    - node_modules
