image: ruby:2.5.0

before_script:
  - apt-get update -qq && apt-get install -y -qq postgres libsqlite3-dev nodejs
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

rspec:
  script:
    - bundle exec rspec

rubocop:
  script:
    - bundle exec rubocop

cache:
  paths:
    - vendor/bundle
    - node_modules
