version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.0
        environment:
          - TARIFF_MEASURES_LOGGER: 0
          - RAILS_ENV: test
          - PG_HOST: localhost
          - PG_USER: ubuntu
          - RACK_ENV: test
      - image: circleci/postgres:9.6.2
        environment:
          - POSTGRES_USER: ubuntu
          - POSTGRES_DB: circleci_test
      - image: redis:3.2.11
    environment:
      - GOVUK_APP_DOMAIN: test
      - DATABASE_URL: "postgres://ubuntu@localhost:5432/circleci_test"
      - TARIFF_SYNC_HOST: "http://example.com"
      - TARIFF_SYNC_USERNAME: "foo"
      - TARIFF_SYNC_PASSWORD: "bar"
      - TARIFF_SYNC_EMAIL: "sync@example.com"
      - TARIFF_FROM_EMAIL: "no-reply@example.com"
      - AWS_ACCESS_KEY_ID: "xxxxxxxxxxxxxxxxxxxx"
      - AWS_SECRET_ACCESS_KEY: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      - AWS_REGION: "us-east-1"
      - AWS_BUCKET_NAME: "trade-tariff-management"
    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: sudo apt-get update -qq && sudo apt-get install -y build-essential postgresql libpq-dev nodejs rake
      - run:
          name: Install bundler
          command: gem install bundler
      # Restore bundle cache
      - restore_cache:
          keys:
            - tariff-{{ checksum "Gemfile.lock" }}
            - tariff-
      - run:
          name: Install gems
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3
      # Store bundle cache
      - save_cache:
          key: tariff-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Set up DB
          command: RAILS_ENV=test bundle exec rake db:create --trace
      - run:
          name: Load DB structure
          command: RAILS_ENV=test SCHEMA=db/structure.sql bundle exec rake db:structure:load --trace
      - run:
          name: "Run Rspec"
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - run:
          name: Run Code Climate Test Coverage Reporter
          command: "RAILS_ENV=test CODECLIMATE_REPO_TOKEN=${CODECLIMATE_REPO_TOKEN} bundle exec codeclimate-test-reporter"
      - store_test_results:
          path: /tmp/test-results
      - deploy:
          command: |
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            cf -v
      - deploy:
          command: |
            curl -v -L -o autopilot https://github.com/contraband/autopilot/releases/download/0.0.3/autopilot-linux
            chmod +x autopilot
            cf install-plugin autopilot -f
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ];
              then CF_ORG=dit-staging CF_SPACE=dev-tariffs CF_APP=tariffs-dev CF_APP_WORKER=tariffs-worker-dev ./bin/deploy
            fi
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "staging" ];
              then CF_ORG=dit-staging CF_SPACE=uat-tariffs CF_APP=tariffs-uat CF_APP_WORKER=tariffs-worker-uat ./bin/deploy
            fi
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "production" ];
              then CF_ORG=dit-staging CF_SPACE=training-tariffs CF_APP=tariffs-training CF_APP_WORKER=tariffs-worker-training ./bin/deploy
            fi
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "production" ];
              then CF_ORG=dit-services CF_SPACE=tariffs CF_APP=tariffs-production CF_APP_WORKER=tariffs-worker-production ./bin/deploy
            fi
