development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: trade_tariff_manangement_development

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV["RAILS_ENV"] == "production" && (JSON.parse(ENV["VCAP_SERVICES"])["redis"].select { |s| s["name"] == ENV["REDIS_INSTANCE_NAME"]}[0]["credentials"]["uri"]).to_s %>
  channel_prefix: trade_tariff_manangement_production
